name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build release binary
        run: |
          mkdir -p release
          cp target/release/log2src release/
          cd release && tar -czf log2src-${{ github.ref_name }}-linux-x64.tar.gz log2src

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/log2src-${{ github.ref_name }}-linux-x64.tar.gz
          draft: true
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
